project_id = "mycvmihdzukmmpyztsrj"

[functions.calculate-risk]
verify_jwt = true

[functions.chat]
verify_jwt = true

[functions.parse-risk-description]
verify_jwt = true

[functions.generate-risk-news]
verify_jwt = true